- name: download artifact
  get_url:
     url: https://github.com/Anji399/big/raw/master/target/big.war
     dest: /tmp
- name: copy artifact
  copy:
     src: /tmp/big.war
     dest: /opt/tomcat/webapps/big.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify: restart tomcat
 
